name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use the GitHub self-hosted runner on your EC2 instance
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy with PM2
        run: |
          pm2 restart your-app-name || pm2 start src/index.js --name your-app-name
          pm2 save
